name: "tfmake"
description: "tfmake GitHub Action."

author: tfmake

branding:
  icon: "box"
  color: "green"

inputs:
  tfmake_context:
    description: "The execution context, plan or apply."
    required: true

  tfmake_log_grouping:
    description: "tfmake log grouping."
    required: false
    default: true

  ignore_modules:
    description: "List of modules to ignore."
    required: false

  touch_files:
    description: "List of files to touch."
    required: false

  tfmake_run_mode:
    description: "tfmake run mode"
    required: false

  tfmake_summary_title:
    description: "tfmake summary title."
    required: false

  pull_request_number:
    description: "Pull Request number."
    required: false

  token:
    description: "GITHUB_TOKEN or Personal Access Token (PAT)."
    required: true
    default: ${{ github.token }}

  working_directory:
    description: "Working directory."
    required: true

runs:
  using: "composite"
  steps:
    - run: bash ${{ github.action_path }}/action.sh
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        TFMAKE_CONTEXT: ${{ inputs.tfmake_context }}
        TFMAKE_LOG_GROUPING: ${{ inputs.tfmake_log_grouping }}
        IGNORE_MODULES: ${{ inputs.ignore_modules }}
        TOUCH_FILES: ${{ inputs.touch_files }}
        TFMAKE_RUN_MODE: ${{ inputs.tfmake_run_mode }}
        TFMAKE_SUMMARY_TITLE: ${{ inputs.tfmake_summary_title }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull_request_number }}
        GH_TOKEN: ${{ inputs.token }}
